version: 2
models:
  - name: int_business_names_flagged
    columns:
      - name: VALID_ABN
        tests:
          - accepted_values:
              values: [0, 1]
      - name: REGISTERED_NO_VALID_ABN
        tests:
          - accepted_values:
              values: [0, 1]
      - name: REVIEW_FLAG
        tests:
          - accepted_values:
              values: [0, 1]